import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const out = process.env.MOSAIC_AUDIT_OUTPUT || '/private/tmp/mosaic-design-audit';
await mkdir(out, { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const results = [];
async function inspect(name) {
  await page.waitForTimeout(350);
  await page.screenshot({ path: `${out}/${name}.png` });
  const audit = await page.evaluate(() => {
    const parse = c => { const n = c.match(/[\d.]+/g)?.map(Number) || []; return n.length === 3 ? [...n, 1] : n; };
    const blend = (top, bottom) => top.slice(0, 3).map((c, i) => c * (top[3] ?? 1) + bottom[i] * (1 - (top[3] ?? 1)));
    const luminance = rgb => { const c = rgb.slice(0, 3).map(x => { const s = x / 255; return s <= .04045 ? s / 12.92 : ((s + .055) / 1.055) ** 2.4; }); return c[0] * .2126 + c[1] * .7152 + c[2] * .0722; };
    const backgrounds = e => { const layers = []; while (e) { layers.push(parse(getComputedStyle(e).backgroundColor)); e = e.parentElement; } return layers.reverse().reduce((bg, layer) => blend(layer, bg), [255, 255, 255]); };
    const contrastIssues = [];
    const root = document.querySelector('dialog[open]') || document.querySelector('.active-session') || document.querySelector('.completion-screen') || document.querySelector('.app-content') || document.querySelector('main');
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) {
      if (!node.textContent.trim()) continue;
      const element = node.parentElement;
      const style = getComputedStyle(element);
      const bounds = element.getBoundingClientRect();
      if (!bounds.width || !bounds.height || style.visibility === 'hidden' || element.closest('.sr-only') || Number(style.opacity) === 0) continue;
      const bg = backgrounds(element), fg = blend(parse(style.color), bg);
      const l = [luminance(bg), luminance(fg)].sort((a, b) => b - a);
      const ratio = (l[0] + .05) / (l[1] + .05);
      const minimum = parseFloat(style.fontSize) >= 24 || parseFloat(style.fontSize) >= 18.66 && Number(style.fontWeight) >= 700 ? 3 : 4.5;
      if (ratio + .01 < minimum) contrastIssues.push({ text: node.textContent.trim().slice(0, 70), ratio: +ratio.toFixed(2), minimum, color: style.color });
    }
    const smallTargets = [...root.querySelectorAll('button, summary')].filter(element => { const r = element.getBoundingClientRect(); return r.width > 0 && r.height > 0 && (r.width < 43.9 || r.height < 43.9); }).map(element => ({ text: element.getAttribute('aria-label') || element.textContent.trim().slice(0, 50), width: element.getBoundingClientRect().width, height: element.getBoundingClientRect().height }));
    return { contrastIssues, smallTargets, overflow: document.documentElement.scrollWidth > innerWidth || root.scrollWidth > root.clientWidth + 1 };
  });
  results.push({ screen: name, ...audit });
}
async function nav(name) { await page.getByRole('navigation').getByRole('button', { name, exact: true }).click(); }
async function scenario(name) { await page.getByRole('button', { name: 'Demo: preview a moment' }).click(); await page.getByRole('dialog').getByRole('button', { name: new RegExp(`^${name}`) }).click(); }
await page.goto('http://127.0.0.1:5173/?intro=1');
await inspect('welcome');
await page.getByRole('button', { name: 'Set up Nudge', exact: true }).click();
await inspect('setup-intentions');
await page.getByRole('button', { name: 'Continue', exact: true }).click();
await inspect('setup-preferences');
await page.getByRole('button', { name: 'Continue', exact: true }).click();
await inspect('setup-connections');
await page.goto('http://127.0.0.1:5173/?intro=1');
await page.evaluate(() => localStorage.removeItem('mosaic-setup-v3')); await page.reload();
await page.getByRole('button', { name: 'Try sample day', exact: true }).click();
await inspect('today');
await page.getByRole('button', { name: 'See calendar and openings', exact: true }).click(); await inspect('calendar-openings'); await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Swap activity', exact: true }).click(); await inspect('swap'); await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Make it easier', exact: true }).click(); await inspect('easier');
await page.getByRole('button', { name: 'I can do that', exact: true }).click(); await inspect('session');
await page.getByRole('button', { name: /^Complete demo action/ }).click(); await page.getByRole('button', { name: 'Better', exact: true }).click(); await inspect('completion');
await page.getByRole('button', { name: 'Keep private & back to my day', exact: true }).click(); await inspect('after-completion');
await scenario('Later busy afternoon'); await inspect('learned-later-afternoon');
await scenario('Busy / no intervention'); await inspect('busy');
await page.getByRole('button', { name: 'See calendar and openings', exact: true }).click(); await inspect('calendar-busy'); await page.keyboard.press('Escape');
await scenario('Evening recharge'); await inspect('evening');
await scenario('Connection recharge'); await inspect('connection-recharge');
await scenario('Evening music recharge'); await inspect('spotify-recharge');
await page.getByRole('button', { name: 'Take one song', exact: true }).click(); await inspect('spotify-session');
await page.getByRole('button', { name: /^Complete demo action/ }).click(); await inspect('spotify-completion');
await page.getByRole('button', { name: 'Helped', exact: true }).click(); await page.getByRole('button', { name: 'Keep private & back to my day', exact: true }).click();
await nav('Rhythm'); await inspect('rhythm');
await page.getByRole('button', { name: /^Sun, 4/ }).click(); await inspect('empty-day'); await page.keyboard.press('Escape');
await nav('You'); await inspect('you');
await page.getByRole('button', { name: 'Edit your preferences' }).click(); await inspect('preferences'); await page.keyboard.press('Escape');
await page.getByRole('button', { name: /^Connections/ }).click(); await inspect('connections'); await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'See activity' }).click(); await inspect('circle'); await page.keyboard.press('Escape');
await page.getByRole('button', { name: /^Settings/ }).click(); await inspect('settings'); await page.keyboard.press('Escape');
await page.getByRole('button', { name: /^How Nudge works/ }).click(); await inspect('guide'); await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Open settings', exact: true }).click();
await page.getByRole('button', { name: 'Replay introduction', exact: true }).click(); await inspect('replay-introduction');
await page.getByRole('button', { name: 'Close introduction', exact: true }).click();
await nav('Today');
await page.getByRole('button', { name: /I need something now/ }).click(); await inspect('choose-intent');
await page.getByRole('button', { name: 'Clear my head', exact: true }).click(); await inspect('choose-time');
await page.getByRole('button', { name: '5 minutes', exact: true }).click(); await inspect('on-demand-action');
await page.getByRole('button', { name: 'Open settings', exact: true }).click();
await page.getByRole('switch', { name: 'Pause Nudge', exact: true }).click(); await page.keyboard.press('Escape'); await inspect('paused');
await page.getByRole('button', { name: 'Resume Nudge', exact: true }).click();
await page.getByRole('button', { name: 'Open settings', exact: true }).click();
await page.getByRole('button', { name: 'Add to home screen', exact: true }).click(); await inspect('install');
await page.getByRole('button', { name: 'Back to Settings', exact: true }).click(); await page.getByRole('button', { name: 'Done', exact: true }).click();
await scenario('Packed afternoon');
await page.getByRole('button', { name: /^How are you feeling/ }).click(); await inspect('check-in');
await page.getByRole('button', { name: 'Overwhelmed', exact: true }).click(); await inspect('overwhelmed-reset');
await page.setViewportSize({ width: 320, height: 667 }); await nav('Today'); await page.getByRole('button', { name: 'Demo: preview a moment' }).click(); await page.getByRole('button', { name: 'Reset sample day', exact: true }).click(); await inspect('today-320'); await nav('Rhythm'); await inspect('rhythm-320');
await page.addStyleTag({ content: 'html { font-size: 200% !important; }' }); await nav('Today'); await inspect('today-large-text'); await page.getByRole('button', { name: 'See calendar and openings', exact: true }).click(); await inspect('calendar-large-text'); await page.keyboard.press('Escape'); await nav('Rhythm'); await inspect('rhythm-large-text'); await nav('You'); await inspect('you-large-text');
await page.setViewportSize({ width: 390, height: 844 }); await page.addStyleTag({ content: 'html { font-size: 100% !important; }' });
await scenario('Evening music recharge'); await inspect('spotify-after-feedback');
await nav('You'); await page.getByRole('button', { name: /^Connections/ }).click(); await inspect('spotify-connections'); await page.keyboard.press('Escape');
await scenario('Packed afternoon'); await page.getByRole('button', { name: 'Demo: preview a moment' }).click(); await page.getByRole('button', { name: 'Reset sample day', exact: true }).click();
await nav('Rhythm'); await inspect('weekly-reflection');
await nav('Today'); await page.getByRole('button', { name: /Indoors or outdoors\?/ }).click(); await inspect('activity-setting');
await page.getByRole('dialog').getByRole('button', { name: 'Outdoors', exact: true }).click(); await inspect('outdoor-personalisation');
await page.getByRole('button', { name: /Indoors or outdoors\?/ }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Indoors', exact: true }).click();
await page.locator('.app-content').evaluate(el => el.scrollTo(0, el.scrollHeight / 2)); await inspect('personal-recharge-calendar');
console.log(JSON.stringify({ output: out, screens: results.length, errors, issues: results.filter(r => r.contrastIssues.length || r.smallTargets.length || r.overflow) }, null, 2));
await browser.close();
