import { useEffect, useRef } from 'react';
import { Activity, ArrowRight, Check, Leaf, Pause, Play, Users } from 'lucide-react';
import type { Action, Completion } from './engine';
import { actions, durationLabel } from './engine';
import { NudgeMark } from './Illustrations';
import { actionIcons } from './presentation';
import './flow-polish.css';
import { MusicCard } from './MusicCard';
import type { SpotifyTrack } from './spotify';
export type Active = { action: Action; remaining: number; deadline: number; paused: boolean; fromFallback: boolean; demoMode: boolean; music?: SpotifyTrack };
export function ActiveSession({ active, onFinish, onDemoFinish, onPause, onEnd }: { active: Active; onFinish: () => void; onDemoFinish: () => void; onPause: () => void; onEnd: () => void }) {
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { heading.current?.focus({ preventScroll: true }); }, []);
  const elapsed = active.action.duration * 60 - active.remaining;
  let passed = 0;
  const stage = active.action.steps.findIndex(step => { passed += step.seconds; return elapsed < passed; });
  const current = active.action.steps[stage < 0 ? active.action.steps.length - 1 : stage];
  const Icon = actionIcons[active.action.icon] || Leaf;
  return <main className={`active-session ${active.action.domain}${active.demoMode ? ' demo-session' : ''}${active.music ? ' music-session' : ''}`} aria-label="Your active action"><header className="session-header"><span className="brand"><NudgeMark />Nudge</span><span className="session-labels"><span className="session-family">{active.action.domain === 'move' ? 'Move' : 'Recharge'}</span>{active.demoMode && <span className="session-demo-label">Demo data</span>}</span></header>{active.music ? <div className="session-content moment-enter"><p className="eyebrow">A LITTLE TIME FOR YOU</p><h1 ref={heading} tabIndex={-1}>One-song reset</h1><p className="music-instruction">Put everything else down.<br />No scrolling. No work. Just listen.</p><MusicCard track={active.music} focused /><div className="timer" role="timer" aria-label={`${active.remaining} seconds remaining`}>{Math.floor(active.remaining / 60)}<span>:</span>{String(active.remaining % 60).padStart(2, '0')}</div><progress aria-label="Time elapsed" value={elapsed} max={active.action.duration * 60} /><span className="timer-status">{active.paused ? 'Paused · take your time' : active.remaining === 0 ? 'Mark it complete when you’ve taken the break.' : 'Your break timer · Spotify plays separately'}</span></div> : <div className="session-content moment-enter"><span className="session-symbol"><Icon size={30} strokeWidth={1.4} /></span><p className="eyebrow">A LITTLE TIME FOR YOU</p><h1 ref={heading} tabIndex={-1}>{active.action.title}</h1><div className="timer" role="timer" aria-label={`${active.remaining} seconds remaining`}>{Math.floor(active.remaining / 60)}<span>:</span>{String(active.remaining % 60).padStart(2, '0')}</div><span className="timer-status">{active.paused ? 'Paused · take your time' : active.remaining === 0 ? 'Ready when you are' : 'At your own pace'}</span><progress aria-label="Time elapsed" value={elapsed} max={active.action.duration * 60} />
    <div className="current-step" aria-live="polite" aria-atomic="true"><p className="eyebrow">{active.remaining === 0 ? 'A SMALL ACTION COUNTS' : active.action.steps.length > 1 ? `STEP ${Math.min(stage + 1 || active.action.steps.length, active.action.steps.length)} OF ${active.action.steps.length}` : 'YOUR MOMENT'}</p><h2>{active.remaining === 0 ? 'Did you take the break?' : current.title}</h2><p>{active.remaining === 0 ? 'Mark it complete when you’ve done the action. A timer can’t tell us that for you.' : current.instruction}</p></div>
    {active.action.steps.length > 1 && <ol className="session-steps" aria-label="Action sequence">{active.action.steps.map((step, index) => <li key={step.title} className={index === stage ? 'current' : ''}><span>{index < stage || active.remaining === 0 ? <Check size={14} /> : index + 1}</span>{step.title}<small>{step.seconds} sec</small></li>)}</ol>}
    </div>}<footer className="session-controls"><button className="primary" onClick={onFinish}>{active.remaining > 0 ? 'Done early' : 'Done'}<Check size={18} /></button>{active.demoMode && <button className="secondary demo-complete-button" onClick={onDemoFinish} aria-describedby="demo-completion-note">Complete demo action<span>Demo</span></button>}<div><button className="plain" onClick={onPause}>{active.paused ? <Play size={16} /> : <Pause size={16} />}{active.paused ? 'Resume' : 'Pause'}</button><button className="plain" onClick={onEnd}>End this action</button></div>{active.demoMode && <p className="session-demo-note" id="demo-completion-note">Demo completion records a sample action without waiting.</p>}</footer></main>;
}
export function CompletionScreen({ name, completion, learning, onFeedback, onShare, onBack }: { name: string; completion: Completion; learning: string; onFeedback: (feedback: string) => void; onShare: () => void; onBack: () => void }) {
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { heading.current?.focus({ preventScroll: true }); }, []);
  const move = completion.domain === 'move';
  const completeDuration = completion.elapsedSeconds !== undefined && completion.elapsedSeconds >= completion.duration * 60;
  const music = actions.find(action => action.id === completion.actionId)?.interest === 'Music';
  const intentionalSeconds = completion.elapsedSeconds ?? completion.duration * 60;
  const title = music && intentionalSeconds > 0 ? `You took ${durationLabel(intentionalSeconds / 60)} for yourself.` : completion.simulated ? move ? `${durationLabel(completion.duration)} of movement.` : `${durationLabel(completion.duration)} to recharge.` : completeDuration ? move ? `You moved for ${durationLabel(completion.duration)}.` : 'You made time to recharge.' : move ? 'A movement break, complete.' : 'A little room for yourself.';
  const negativeFeedback = ['More tired', 'Not better', 'Didn’t feel right', "Didn't feel right", 'Not for me'].includes(completion.feedback || '');
  return <main className={`completion-screen page ${completion.domain}`}><div className="completion-seal" aria-hidden="true"><Check size={32} strokeWidth={1.6} /></div><p className="eyebrow">{completion.simulated ? 'DEMO ACTION COMPLETED' : 'SMALL ACTION. REAL LIFE.'}</p><h1 ref={heading} tabIndex={-1}>{title}</h1><p className="completion-detail">{completion.title} · {completion.simulated ? 'sample completion' : 'marked complete'}</p><section className="feedback-section"><h2>How was that?</h2><p>Optional. No difference is an answer too.</p><div className="feedback-options">{(move ? ['Better', 'No different', 'Didn’t feel right'] : ['Helped', 'No different', 'Not for me']).map(value => <button key={value} aria-pressed={completion.feedback === value} onClick={() => onFeedback(value)}>{value}{completion.feedback === value && <Check size={14} />}</button>)}</div></section>
    <div className="completion-learning" role="status"><span>{move ? <Activity size={20} /> : <Leaf size={20} />}</span><div><h2>{completion.feedback ? 'Got it. We’ll remember.' : 'What Nudge takes forward'}</h2><p>{negativeFeedback ? 'We’ll give this activity less weight and try a gentler or different option next time.' : learning}</p></div></div>
    <section className="share-section"><h2><Users size={18} />{completion.shared ? 'Shared in your sample Circle' : 'Share with Circle?'}</h2><p className="share-preview">“{completion.domain === 'move' ? `${name} took a movement break ✓` : `${name} made time to recharge ✓`}”</p><p className="source-note">Only the action appears in this Circle preview. Health and schedule stay private.</p>{!completion.shared && <button className="text-button" onClick={onShare}>Share this action<ArrowRight size={16} /></button>}</section>
    <button className="primary" onClick={onBack}>{completion.shared ? 'Back to my day' : 'Keep private & back to my day'}<ArrowRight size={18} /></button>
  </main>;
}
