import { useState } from 'react';
import { Activity, CalendarDays, Check, ChevronRight, Leaf, LockKeyhole, Settings2 } from 'lucide-react';
import type { Completion, State } from './engine';
import { durationLabel, learningInsights, stateDate } from './engine';
import { Sheet } from './Sheet';
import './rhythm-polish.css';
import { completedSeconds, reflectionTime, weeklyReflection } from './reflection';
export type Panel = 'preferences' | 'connections' | 'circle' | 'settings' | 'guide' | 'mood' | 'demo';
export function Avatars({ people = ['Jay', 'Maya', 'Vijay'] }: { people?: string[] }) { return <span className="avatars" aria-hidden="true">{people.map((name, index) => <i key={`${name}-${index}`}>{name.trim().slice(0, 1).toUpperCase()}</i>)}</span>; }
export function ActionHistory({ items, sharedName }: { items: Completion[]; sharedName?: string }) {
  return <ul className="action-history">{items.map(item => <li key={item.id}><span className={`history-symbol ${item.domain}`}>{item.domain === 'move' ? <Activity size={18} /> : <Leaf size={18} />}</span><div><strong>{sharedName ? item.domain === 'move' ? `${sharedName} took a movement break` : `${sharedName} made time to recharge` : item.title}</strong>{sharedName ? <p>Shared in your sample Circle</p> : <><p>{item.time} · {durationLabel(completedSeconds(item) / 60)}{item.demo ? ' · example' : item.simulated ? ' · demo completion' : ''}</p>{item.feedback && <small>Your feedback: {item.feedback}</small>}</>}</div><Check size={17} aria-label="Completed" /></li>)}</ul>;
}
export function Rhythm({ state }: { state: State }) {
  const today = stateDate(state);
  const [selected, setSelected] = useState(today);
  const [showDay, setShowDay] = useState(false);
  const monday = new Date(`${today}T12:00:00`);
  monday.setDate(monday.getDate() - (monday.getDay() + 6) % 7);
  const days = Array.from({ length: 7 }, (_, index) => { const date = new Date(monday); date.setDate(date.getDate() + index); return { key: `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`, label: date.toLocaleDateString('en-US', { weekday: 'short' }), number: date.getDate() }; });
  const week = state.completions.filter(c => c.date >= days[0].key && c.date <= days[6].key);
  const dayItems = state.completions.filter(c => c.date === selected).sort((a, b) => (a.contextHour ?? 0) * 60 + (a.contextMinute ?? 0) - ((b.contextHour ?? 0) * 60 + (b.contextMinute ?? 0)));
  const reflection = weeklyReflection(state);
  const observations = learningInsights(state);
  const contextSummary = [
    state.context.sleepMinutes !== null ? `${Math.floor(state.context.sleepMinutes / 60)}h ${state.context.sleepMinutes % 60}m sleep` : null,
    state.context.steps !== null ? `${state.context.steps.toLocaleString()} steps` : null,
    state.context.meetings !== null ? `${state.context.meetings} meetings` : null,
  ].filter(Boolean).join(' · ');
  return <section className="page rhythm-page" aria-labelledby="rhythm-heading"><header className="page-heading"><p className="eyebrow">YOUR RHYTHM</p><h1 id="rhythm-heading" tabIndex={-1}>Your rhythm</h1><p>What Nudge is learning about your days.</p></header>
    <section className="weekly-reflection" aria-labelledby="reflection-heading"><p className="eyebrow" id="reflection-heading">THIS WEEK</p><h2>{reflection.totalMinutes ? `${reflectionTime(reflection.totalMinutes).replace(' min', ' minutes').replace(' sec', ' seconds')} for yourself` : reflection.totalMoments ? 'A little room for yourself' : 'Room for a small beginning'}</h2><p>Small moments added up.</p><strong className="reflection-moments">{reflection.totalMoments} {reflection.totalMoments === 1 ? 'moment' : 'moments'}</strong><div className="reflection-families"><div><span><Activity size={16} />MOVE</span><strong>{reflection.moveMoments} {reflection.moveMoments === 1 ? 'moment' : 'moments'}</strong><p>{reflectionTime(reflection.moveMinutes)}</p></div><div><span><Leaf size={16} />RECHARGE</span><strong>{reflection.rechargeMoments} {reflection.rechargeMoments === 1 ? 'moment' : 'moments'}</strong><p>{reflectionTime(reflection.rechargeMinutes)}</p></div></div><p className="source-note">{state.demoMode ? `${reflection.exampleMoments} example moments · ${reflection.newMoments} new demo ${reflection.newMoments === 1 ? 'choice' : 'choices'}. Sample week, not your personal history.` : 'Time you marked as taken for yourself. Even a short break counts.'}</p></section>
    <section className="week-section week-mosaic" aria-labelledby="week-heading"><div className="section-heading"><h2 id="week-heading">Your little moments</h2><span>{monday.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} – {new Date(`${days[6].key}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span></div>
      <p className="mosaic-caption">Small things add up.</p>
      <div className="week-days mosaic-days">{days.map(day => { const items = week.filter(c => c.date === day.key); const moves = items.filter(c => c.domain === 'move').length; const resets = items.filter(c => c.domain === 'recharge').length; return <button key={day.key} className={selected === day.key ? 'selected' : ''} aria-pressed={selected === day.key} aria-label={`${day.label}, ${day.number}: ${moves} Move, ${resets} Recharge${day.key === today ? ', today' : ''}`} onClick={() => { setSelected(day.key); setShowDay(true); }}><span>{day.label.slice(0, 1)}</span><strong>{day.number}</strong><span className="mosaic-day-tiles" aria-hidden="true">{items.length ? items.map(item => <i key={item.id} className={`mosaic-tile ${item.domain}`} />) : <i className="mosaic-empty" />}</span></button>; })}</div>
      <div className="week-totals mosaic-legend"><span><Activity size={16} /><strong>{week.filter(c => c.domain === 'move').length}</strong> Move</span><span><Leaf size={16} /><strong>{week.filter(c => c.domain === 'recharge').length}</strong> Recharge</span></div>
      <p className="source-note">One tile for each completed action. Tap a day to look back.{state.demoMode && ' Example actions included.'}</p>
    </section>
    <section className="activity-breakdown"><div className="section-heading"><h2>What those moments looked like</h2></div>{Object.keys(reflection.activityBreakdown).length ? <ul>{Object.entries(reflection.activityBreakdown).map(([activity, count]) => <li key={activity}><span>{activity}</span><strong>× {count}</strong></li>)}</ul> : <p className="empty-copy">Your completed Move and Recharge actions will appear here.</p>}{reflection.musicMinutes > 0 && <p className="source-note">{state.demoMode ? 'In this sample week, music made' : 'You made'} {reflectionTime(reflection.musicMinutes)} {state.demoMode ? 'of room away from work.' : 'for music this week. Intentional Recharge time, not listening statistics.'}</p>}</section>
    <section className="learning-section" aria-label="Observations from your choices"><div className="section-heading"><h2>Nudge is learning</h2></div><div className="learning-list">{observations.map(item => <article key={item.id} className={`learning-observation learning-${item.id}`}><span className="observation-symbol" aria-hidden="true">{item.id === 'recharge' ? <Leaf size={19} /> : <Activity size={19} />}</span><div><h2>{item.title}</h2><p>{item.detail}</p></div></article>)}</div>{state.demoMode && <p className="source-note learning-source">Example history is a preview. Only your new choices change future suggestions.</p>}{state.demoMode && reflection.newMoments === 0 && <details className="example-learning"><summary>Example of what Nudge could learn</summary><p className="source-note">Illustrative patterns, not conclusions from your personal choices.</p><article><h3>Short movement can fit busy afternoons</h3><p>Repeated short completions could help Nudge lower the effort next time.</p></article><article><h3>Music can become an evening reset</h3><p>Choosing music and saying it helped could make it more relevant.</p></article></details>}</section>
    <section className="rhythm-recent"><div className="section-heading"><h2>Today’s actions</h2><span>{state.demoMode ? 'Sample day' : 'Today'}</span></div>{state.completions.some(c => c.date === today) ? <ActionHistory items={state.completions.filter(c => c.date === today).slice().reverse()} /> : <p className="empty-copy">Your first completed action will appear here. A small start is enough.</p>}</section>
    {showDay && <Sheet title={new Date(`${selected}T12:00:00`).toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })} onClose={() => setShowDay(false)}>{selected === today && <p className="sheet-description">{contextSummary || 'No context recorded for today.'}{state.demoMode && contextSummary && ' · sample context'}</p>}{dayItems.length ? <ActionHistory items={dayItems} /> : <div className="empty-state"><Leaf size={28} /><h3>A little room to begin.</h3><p>No actions recorded for this day. There’s no missed target to catch up with.</p></div>}</Sheet>}
  </section>;
}
export function YouPage({ state, onOpen }: { state: State; onOpen: (panel: Panel) => void }) {
  const p = state.preferences;
  return <section className="page you-page" aria-labelledby="you-heading"><header className="page-heading"><p className="eyebrow">YOUR KIND OF WELLBEING</p><h1 id="you-heading" tabIndex={-1}>You</h1><p>A little care, on your terms.</p></header>
    <div className="profile-line"><span className="profile-avatar">{(p.name || 'Y')[0].toUpperCase()}</span><div><h2>{p.name || 'Your space'}</h2><p>{state.demoMode ? 'Exploring a sample day' : 'Everything stays on this device'}</p></div><button className="icon-button" aria-label="Edit your preferences" onClick={() => onOpen('preferences')}><Settings2 size={20} /></button></div>
    <section className="you-section"><div className="section-heading"><h2>What helps you move</h2><button className="text-button" onClick={() => onOpen('preferences')}>Edit<span className="sr-only"> movement preferences</span></button></div>{p.movementPreferences.length ? <ul className="preference-tags">{p.movementPreferences.map(item => <li key={item}>{item}</li>)}</ul> : <p className="empty-copy">Choose the kinds of movement that feel comfortable.</p>}</section>
    <section className="you-section"><div className="section-heading"><h2>What helps you recharge</h2><button className="text-button" onClick={() => onOpen('preferences')}>Edit<span className="sr-only"> recharge preferences</span></button></div>{p.interests.length ? <ul className="preference-tags recharge-tags">{p.interests.map(item => <li key={item}>{item}</li>)}</ul> : <p className="empty-copy">Music, company, creativity or quiet. Choose what feels like you.</p>}</section>
    <section className="you-section"><div className="section-heading"><h2>Your Circle</h2><button className="text-button" onClick={() => onOpen('circle')}>See activity</button></div><div className="circle-people">{['Jay', 'Maya', 'Vijay'].map((name, index) => <span key={name}><i className={`avatar-${index}`}>{name[0]}</i>{name}</span>)}</div><p className="source-note">Sample Circle. Only the actions you choose to share are visible.</p></section>
    <div className="you-links">{[{ title: 'Connections', detail: 'Calendar, health and Spotify', icon: CalendarDays, target: 'connections' as const }, { title: 'Settings', detail: 'Nudges, quiet hours and privacy', icon: Settings2, target: 'settings' as const }, { title: 'How Nudge works', detail: 'Context → action → adapt → learn', icon: Leaf, target: 'guide' as const }].map(({ title, detail, icon: Icon, target }) => <button key={target} onClick={() => onOpen(target)}><Icon size={21} /><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight size={19} /></button>)}</div>
    <p className="privacy-footer"><LockKeyhole size={16} />Your health context stays private.</p>
  </section>;
}
